# Generated by Django 4.2 on 2023-04-20 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=20000)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2023, 4, 20, 4, 51, 16, 894440, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.TextField(max_length=100)),
                ('project_abstract', models.TextField(max_length=800)),
                ('project_tech', models.TextField(max_length=60)),
                ('project_programming_background', models.TextField(max_length=60)),
                ('project_link', models.TextField(max_length=100)),
                ('project_img', models.ImageField(default='./static/img/logo1.JPG', upload_to='')),
            ],
        ),
    ]
