# Generated by Django 3.2.7 on 2023-04-10 05:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mybio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetable',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 5, 40, 44, 806112, tzinfo=utc)),
        ),
    ]
