# Generated by Django 3.2.7 on 2023-04-13 09:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mybio', '0002_messagetable_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.TextField(max_length=100)),
                ('project_abstract', models.TimeField(max_length=400)),
                ('project_tech', models.TextField(max_length=60)),
                ('project_programming_background', models.TextField(max_length=60)),
                ('project_link', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='messagetable',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 9, 5, 5, 3598, tzinfo=utc)),
        ),
    ]
