# Generated by Django 4.2 on 2023-04-20 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybio', '0003_alter_messagetable_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetable',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 6, 17, 50, 367575, tzinfo=datetime.timezone.utc)),
        ),
    ]
