# Generated by Django 3.2.7 on 2023-04-13 10:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mybio', '0004_alter_messagetable_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetable',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 10, 7, 44, 444652, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projecttable',
            name='project_title',
            field=models.TextField(max_length=10),
        ),
    ]
