# Generated by Django 3.2.7 on 2023-04-13 10:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mybio', '0006_auto_20230413_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetable',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 10, 9, 46, 329612, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projecttable',
            name='project_title',
            field=models.TextField(max_length=100),
        ),
    ]
