# Generated by Django 3.2.7 on 2023-04-18 10:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mybio', '0010_alter_messagetable_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetable',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 10, 42, 10, 171631, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projecttable',
            name='project_abstract',
            field=models.TextField(max_length=800),
        ),
    ]
